global:
  resolve_timeout: 5m

route:
  receiver: 'email-notifications'

receivers:
- name: 'email-notifications'
  email_configs:
  - to: 'admin@example.com'
    from: 'alertmanager@example.com'
    smarthost: 'smtp.example.com:25'
    auth_username: 'alertmanager'
    auth_password: 'password'
